import type { TextInputComponent } from "./text-input.ts";
import type { TextAreaComponent } from "./text-area.ts";
import type { NumberInputComponent } from "./number-input.ts";
import type { DateInputComponent } from "./date-input.ts";
import type { DateTimeInputComponent } from "./date-time-input.ts";
import type { TimeInputComponent } from "./time-input.ts";
import type { SliderInputComponent } from "./slider-input.ts";
import type { SpinnerInputComponent } from "./spinner-input.ts";
import type { OptionDisplayComponent } from "./option-display.ts";
import type { SelectInputComponent } from "./select-input.ts";
import type { RadioButtonComponent } from "./radio-button.ts";
import type { RadioButtonListComponent } from "./radio-button-list.ts";
import type { CheckboxComponent } from "./checkbox.ts";
import type { CheckboxListComponent } from "./checkbox-list.ts";
import type { MultiSelectInputComponent } from "./multi-select-input.ts";
import type { CustomOptionFormComponent } from "./custom-option-form.ts";
import type { ErrorsComponent } from "./errors.ts";
import type { LabelComponent } from "./label.ts";
import type { QuestionScaffoldComponent } from "./question-scaffold.ts";
import type { OptionsLoadingComponent } from "./options-loading.ts";
import type { HelpComponent } from "./help.ts";
import type { LegalComponent } from "./legal.ts";
import type { FlyoverComponent } from "./flyover.ts";
import type { HeaderComponent } from "./header.ts";
import type { FooterComponent } from "./footer.ts";
import type { FormComponent } from "./form.ts";
import type { StackComponent } from "./stack.ts";
import type { AnswerListComponent } from "./answer-list.ts";
import type { AnswerScaffoldComponent } from "./answer-scaffold.ts";
import type { GroupListComponent } from "./group-list.ts";
import type { GroupScaffoldComponent } from "./group-scaffold.ts";
import type { TableComponent } from "./table.ts";
import type { InputGroupComponent } from "./input-group.ts";
import type { FileInputComponent } from "./file-input.ts";
import type { DisplayRendererComponent } from "./display-renderer.ts";
import type { TabContainerComponent } from "./tab-container.ts";
import type { LinkComponent } from "./link.ts";

export * from "./text-input.ts";
export * from "./text-area.ts";
export * from "./number-input.ts";
export * from "./date-input.ts";
export * from "./date-time-input.ts";
export * from "./time-input.ts";
export * from "./slider-input.ts";
export * from "./spinner-input.ts";
export * from "./option-display.ts";
export * from "./option-item.ts";
export * from "./select-input.ts";
export * from "./radio-button.ts";
export * from "./radio-button-list.ts";
export * from "./checkbox.ts";
export * from "./checkbox-list.ts";
export * from "./multi-select-input.ts";
export * from "./custom-option-form.ts";
export * from "./errors.ts";
export * from "./label.ts";
export * from "./question-scaffold.ts";
export * from "./options-loading.ts";
export * from "./help.ts";
export * from "./legal.ts";
export * from "./flyover.ts";
export * from "./header.ts";
export * from "./footer.ts";
export * from "./form.ts";
export * from "./stack.ts";
export * from "./answer-list.ts";
export * from "./answer-scaffold.ts";
export * from "./group-list.ts";
export * from "./group-scaffold.ts";
export * from "./table.ts";
export * from "./input-group.ts";
export * from "./file-input.ts";
export * from "./display-renderer.ts";
export * from "./tab-container.ts";
export * from "./link.ts";

export type Theme = {
  TextInput: TextInputComponent;
  TextArea: TextAreaComponent;
  NumberInput: NumberInputComponent;
  DateInput: DateInputComponent;
  DateTimeInput: DateTimeInputComponent;
  TimeInput: TimeInputComponent;
  SliderInput: SliderInputComponent;
  SpinnerInput: SpinnerInputComponent;
  OptionDisplay: OptionDisplayComponent;
  SelectInput: SelectInputComponent;
  RadioButton: RadioButtonComponent;
  RadioButtonList: RadioButtonListComponent;
  Checkbox: CheckboxComponent;
  CheckboxList: CheckboxListComponent;
  MultiSelectInput: MultiSelectInputComponent;
  CustomOptionForm: CustomOptionFormComponent;
  Errors: ErrorsComponent;
  Label: LabelComponent;
  QuestionScaffold: QuestionScaffoldComponent;
  OptionsLoading: OptionsLoadingComponent;
  Help: HelpComponent;
  Legal: LegalComponent;
  Flyover: FlyoverComponent;
  Header: HeaderComponent;
  Footer: FooterComponent;
  Form: FormComponent;
  Stack: StackComponent;
  AnswerList: AnswerListComponent;
  AnswerScaffold: AnswerScaffoldComponent;
  GroupList: GroupListComponent;
  GroupScaffold: GroupScaffoldComponent;
  Table: TableComponent;
  InputGroup: InputGroupComponent;
  FileInput: FileInputComponent;
  DisplayRenderer: DisplayRendererComponent;
  TabContainer: TabContainerComponent;
  Link: LinkComponent;
};
